from enum import Enum, IntEnum
from utils import ArgTypeMixin

FRAME_START_SYMBOL = b'\x12'

class ImageType(ArgTypeMixin, IntEnum):
    RAW_FULL = 0
    RAW_PART = 1
    COMP_FULL = 2
    COMP_PART = 3

class CmrMode(ArgTypeMixin, Enum):
    SLEEP = 0 
    SD = 1
    HD = 2

class Baudrate(ArgTypeMixin, IntEnum):
    BR9600 = 0
    BR115200 = 1

class MDMode(ArgTypeMixin, Enum):
    FULLSTEP = 0 
    HALFSTEP_FAST = 1
    HALFSTEP_SLOW = 2


MEMORY_SLOT_TYPE = int
MEMORY_SLOT_VALUES = [0, 1, 2, 3]

IMAGE_LINE_TYPE = int
IMAGE_LINE_VALUES = range(0, 481) #tmp

PREVIEW_TYPE = int
PREVIEW_VALUES = [0, 1]

PART_TYPE = int
PART_VAL = range(0, 30)

DETECT_TYPE = int
DETECT_VALUES = [0, 1]

ENABLE_TYPE = int
ENABLE_VALUES = [0, 1]

STEPS_TYPE = int

PERIOD_TYPE = int

DIR_TYPE = int
DIR_VALUES = [0, 1]

POWER_TYPE = int

RESISTOR_ID_TYPE = int

class ModuleId(Enum):
    SEN = 0
    PM = 1
    MD = 2
    CMR = 3
    COM = 4
    SUP = 5

class CmdId(Enum):
    SUP_C_IDLE = 0
    SUP_C_TRIGGER_HAPPY_PATH = 1
    SUP_C_RUN_PARTIAL_HAPPY_PATH = 2

    CMR_C_SET_MODE = 20
    CMR_C_CAPTURE = 21
    CMR_C_DOWNLOAD = 22
    CMR_C_DOWNLOAD_LINE = 23
    CMR_C_SET_EXPOSURE = 24

    COM_C_PING = 40

    COM_C_SEND = 41
    COM_C_SEND_IMAGE = 42
    COM_C_SEND_IMAGE_PREV = 43
    COM_C_SEND_ERROR = 44

    PM_C_CUT_THERMAL_KNIFE = 60
    PM_C_STOP_THERMAL_KNIFE = 61
    PM_C_RAD_POWER = 62
    PM_C_CAM_POWER = 63
    PM_C_MRAM_POWER = 64
    PM_C_TURN_ON_LED = 65
    PM_C_TURN_OFF_LED = 66

    SEN_C_ICM_INITIALIZATION = 80
    SEN_C_MMC_INITIALIZATION = 81
    SEN_C_RDN_INITIALIZATION = 82
    SEN_C_GET_ALL = 83
    SEN_C_GET_ICM = 84
    SEN_C_GET_MMC = 85
    SEN_C_GET_RDN = 86
    SEN_C_GET_ENC = 87
    SEN_C_GET_ENDSTOPS = 88

    MD_C_ENABLE = 100
    MD_C_STEPS = 101
    MD_C_ON_INF = 102
    MD_C_SET_SPEED = 103
    MD_C_SET_DIR = 104
    MD_C_STOP = 105
    MD_C_OFF = 106
    MD_C_STEP_IGNORE_ENDSTOP = 107

TEXT_FRAME = b'\x00'
IMAGE_FRAME = b'\x01'
IMAGE_PREV_FRAME = b'\x02'
ERROR_FRAME = b'\x03'
CPS_IMG_FRAME = b'\x04'
IMG_INIT_FRAME = b'\x05'

TEXT_FRAME_PAYLOAD_SIZE = 200
IMAGE_FRAME_PAYLOAD_SIZE = 640
IMAGE_PREV_FRAME_PAYLOAD_SIZE = 64
ERROR_FRAME_PAYLOAD_SIZE = 4
IMAGE_PART_SIZE = 150
IMG_INIT_SIZE=5

frame_sizes = {
    TEXT_FRAME : TEXT_FRAME_PAYLOAD_SIZE,
    IMAGE_FRAME : IMAGE_FRAME_PAYLOAD_SIZE, 
    IMAGE_PREV_FRAME : IMAGE_PREV_FRAME_PAYLOAD_SIZE,
    ERROR_FRAME : ERROR_FRAME_PAYLOAD_SIZE,
    CPS_IMG_FRAME : IMAGE_PART_SIZE, 
    IMG_INIT_FRAME : IMG_INIT_SIZE 
}