# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frames_proto/lunaris_downlink.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'frames_proto/lunaris_downlink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#frames_proto/lunaris_downlink.proto\x12\x17lunaris_downlink_frames\".\n\x0bIMUAxisData\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\".\n\x0bMagAxisData\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\xb3\x04\n\nSensorData\x12:\n\x0cicm_gyr_data\x18\x01 \x01(\x0b\x32$.lunaris_downlink_frames.IMUAxisData\x12:\n\x0cicm_acc_data\x18\x02 \x01(\x0b\x32$.lunaris_downlink_frames.IMUAxisData\x12\x10\n\x08icm_temp\x18\x03 \x01(\x05\x12:\n\x0cmmc_mag_data\x18\x04 \x01(\x0b\x32$.lunaris_downlink_frames.MagAxisData\x12\x10\n\x08mmc_temp\x18\x05 \x01(\x05\x12\x17\n\x0frdn_serial_dose\x18\x06 \x01(\r\x12\x15\n\rrdn_sen1_dose\x18\x07 \x01(\r\x12\x15\n\rrdn_sen2_dose\x18\x08 \x01(\r\x12\x1c\n\x14rdn_serial_intensity\x18\t \x01(\r\x12\x1a\n\x12rdn_sen1_intensity\x18\n \x01(\r\x12\x1a\n\x12rdn_sen2_intensity\x18\x0b \x01(\r\x12\x10\n\x08rdn_temp\x18\x0c \x01(\x05\x12\x0f\n\x07rdn_vdd\x18\r \x01(\x05\x12\x16\n\x0erdn_crystal_ok\x18\x0e \x01(\x08\x12\x15\n\rrdn_analog_ok\x18\x0f \x01(\x08\x12\x16\n\x0e\x65ncoder_sensor\x18\x10 \x01(\r\x12\x14\n\x0chall_endstop\x18\x11 \x01(\r\x12\x1a\n\x12reflective_endstop\x18\x12 \x01(\r\x12\x14\n\x0clight_sensor\x18\x13 \x01(\r\"~\n\x0eTelemetryFrame\x12\x36\n\nframe_type\x18\x01 \x01(\x0e\x32\".lunaris_downlink_frames.FrameType\x12\x34\n\x07payload\x18\x02 \x01(\x0b\x32#.lunaris_downlink_frames.SensorData*\xa5\x01\n\tFrameType\x12\x16\n\x12\x46T_DEBUG_LOG_FRAME\x10\x00\x12\x12\n\x0e\x46T_IMAGE_FRAME\x10\x01\x12\x17\n\x13\x46T_IMAGE_PREV_FRAME\x10\x02\x12\x12\n\x0e\x46T_ERROR_FRAME\x10\x03\x12\x10\n\x0c\x46T_IMG_FRAME\x10\x04\x12\x15\n\x11\x46T_IMG_INIT_FRAME\x10\x05\x12\x16\n\x12\x46T_TELEMETRY_FRAME\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frames_proto.lunaris_downlink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETYPE']._serialized_start=855
  _globals['_FRAMETYPE']._serialized_end=1020
  _globals['_IMUAXISDATA']._serialized_start=64
  _globals['_IMUAXISDATA']._serialized_end=110
  _globals['_MAGAXISDATA']._serialized_start=112
  _globals['_MAGAXISDATA']._serialized_end=158
  _globals['_SENSORDATA']._serialized_start=161
  _globals['_SENSORDATA']._serialized_end=724
  _globals['_TELEMETRYFRAME']._serialized_start=726
  _globals['_TELEMETRYFRAME']._serialized_end=852
# @@protoc_insertion_point(module_scope)
